<a href="https://colab.research.google.com/github/TanViCh0UhAn12/ML/blob/main/ANN_classi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ANN --Artificial Neural Network**
**Classification**

*1. Importing Libraries*

In [211]:
import seaborn as sns
import pandas as pd
import numpy as np

*2. Reading Dataset*

In [212]:
churn = pd.read_csv('/content/Churn_Modelling.csv')

*3. Analyzing data set*

In [213]:
df = churn
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [214]:
df.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [215]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [216]:
df.corr()

RowNumber  CustomerId  CreditScore       Age    Tenure  \
RowNumber         1.000000    0.004202     0.005840  0.000783 -0.006495   
CustomerId        0.004202    1.000000     0.005308  0.009497 -0.014883   
CreditScore       0.005840    0.005308     1.000000 -0.003965  0.000842   
Age               0.000783    0.009497    -0.003965  1.000000 -0.009997   
Tenure           -0.006495   -0.014883     0.000842 -0.009997  1.000000   
Balance          -0.009067   -0.012419     0.006268  0.028308 -0.012254   
NumOfProducts     0.007246    0.016972     0.012238 -0.030680  0.013444   
HasCrCard         0.000599   -0.014025    -0.005458 -0.011721  0.022583   
IsActiveMember    0.012044    0.001665     0.025651  0.085472 -0.028362   
EstimatedSalary  -0.005988    0.015271    -0.001384 -0.007201  0.007784   
Exited           -0.016571   -0.006248    -0.027094  0.285323 -0.014001   

                  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber       -0.009067       0.007246   0.000599        0.012044   
CustomerId      -0.012419       0.016972  -0.014025        0.001665   
CreditScore      0.006268       0.012238  -0.005458        0.025651   
Age              0.028308      -0.030680  -0.011721        0.085472   
Tenure          -0.012254       0.013444   0.022583       -0.028362   
Balance          1.000000      -0.304180  -0.014858       -0.010084   
NumOfProducts   -0.304180       1.000000   0.003183        0.009612   
HasCrCard       -0.014858       0.003183   1.000000       -0.011866   
IsActiveMember  -0.010084       0.009612  -0.011866        1.000000   
EstimatedSalary  0.012797       0.014204  -0.009933       -0.011421   
Exited           0.118533      -0.047820  -0.007138       -0.156128   

                 EstimatedSalary    Exited  
RowNumber              -0.005988 -0.016571  
CustomerId              0.015271 -0.006248  
CreditScore            -0.001384 -0.027094  
Age                    -0.007201  0.285323  
Tenure                  0.007784 -0.014001  
Balance                 0.012797  0.118533  
NumOfProducts           0.014204 -0.047820  
HasCrCard              -0.009933 -0.007138  
IsActiveMember         -0.011421 -0.156128  
EstimatedSalary         1.000000  0.012097  
Exited                  0.012097  1.000000

In [217]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [218]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [219]:
df.nunique()

RowNumber          10000
CustomerId         10000
Surname             2932
CreditScore          460
Geography              3
Gender                 2
Age                   70
Tenure                11
Balance             6382
NumOfProducts          4
HasCrCard              2
IsActiveMember         2
EstimatedSalary     9999
Exited                 2
dtype: int64

*4. Label Encoding* : - 
In this dataset, no need to do labeling as in y already we have 0 & 1 as a output which is considered as a label itself.

In [220]:
df['Exited'].unique()

array([1, 0])

*5. Defining variables x & y*

In [221]:
x=df.iloc[:,7:13]
y=df['Exited']
x.head(),y.head()

(   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
 0       2       0.00              1          1               1   
 1       1   83807.86              1          0               1   
 2       8  159660.80              3          1               0   
 3       1       0.00              2          0               0   
 4       2  125510.82              1          1               1   
 
    EstimatedSalary  
 0        101348.88  
 1        112542.58  
 2        113931.57  
 3         93826.63  
 4         79084.10  ,
 0    1
 1    0
 2    1
 3    0
 4    0
 Name: Exited, dtype: int64)

*6. Feature Scaling in x dependent variable*


In [222]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
mmsx=mms.fit_transform(x)
print(mmsx[:9])
print(pd.DataFrame(mmsx).describe())

[[0.2        0.         0.         1.         1.         0.50673489]
 [0.1        0.33403148 0.         0.         1.         0.56270874]
 [0.8        0.63635718 0.66666667 1.         0.         0.56965435]
 [0.1        0.         0.33333333 0.         0.         0.46912005]
 [0.2        0.50024622 0.         1.         1.         0.39540036]
 [0.8        0.45339436 0.33333333 1.         0.         0.74879716]
 [0.7        0.         0.33333333 1.         1.         0.0502609 ]
 [0.4        0.45853972 1.         1.         0.         0.59673349]
 [0.4        0.56617039 0.33333333 0.         1.         0.37468038]]
                  0             1             2            3             4  \
count  10000.000000  10000.000000  10000.000000  10000.00000  10000.000000   
mean       0.501280      0.304848      0.176733      0.70550      0.515100   
std        0.289217      0.248696      0.193885      0.45584      0.499797   
min        0.000000      0.000000      0.000000      0.00000      

*7. Label Binarizer*

In [223]:
ys=y.squeeze()
pdy=pd.get_dummies(ys).values
print(pdy[:8])

[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]


*8. Split data set in train & test*

In [224]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(mmsx,pdy, test_size=.25, random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7500, 6)
(2500, 6)
(7500, 2)
(2500, 2)


*9. Import libraries & build Neural N/w Model*

In [225]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy, binary_crossentropy


In [226]:
model= Sequential([
Dense(units=5, input_dim=6, activation='relu'),
Dense(units=20, activation='relu'),
Dense(units=2, activation='sigmoid')
])

In [227]:
model.compile (optimizer='Adam', loss='binary_crossentropy', metrics='accuracy')

In [228]:
model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_59 (Dense)            (None, 5)                 35        
                                                                 
 dense_60 (Dense)            (None, 20)                120       
                                                                 
 dense_61 (Dense)            (None, 2)                 42        
                                                                 
Total params: 197
Trainable params: 197
Non-trainable params: 0
_________________________________________________________________


In [229]:
d=model.fit(x_train, y_train,batch_size=150,epochs=100)

Epoch 1/100
50/50 [==============================] - 2s 5ms/step - loss: 0.5799 - accuracy: 0.7963
Epoch 2/100
50/50 [==============================] - 0s 3ms/step - loss: 0.5197 - accuracy: 0.7963
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 0.5080 - accuracy: 0.7963
Epoch 4/100
50/50 [==============================] - 0s 3ms/step - loss: 0.5027 - accuracy: 0.7963
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4989 - accuracy: 0.7963
Epoch 6/100
50/50 [==============================] - 0s 3ms/step - loss: 0.4970 - accuracy: 0.7963
Epoch 7/100
50/50 [==============================] - 0s 3ms/step - loss: 0.4946 - accuracy: 0.7963
Epoch 8/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4934 - accuracy: 0.7963
Epoch 9/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4923 - accuracy: 0.7963
Epoch 10/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4914 - accuracy: 0.7963
Epoch 11/

*10. Model Prediction*

In [230]:
y_pred1=model.predict(x_test)
y_pred1

79/79 [==============================] - 0s 2ms/step


array([[0.80946285, 0.19280027],
       [0.6129351 , 0.38009977],
       [0.82439595, 0.17580312],
       ...,
       [0.6089978 , 0.382673  ],
       [0.8408121 , 0.15484154],
       [0.6455453 , 0.348683  ]], dtype=float32)

In [231]:
y_test_class = np.argmax(y_test, axis=1)
y_pred1_class= np.argmax(y_pred1, axis=1)
y_pred1_class, y_test_class

(array([0, 0, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]))

*11. Model Evaluation*

In [232]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test_class, y_pred1_class))
print(classification_report(y_test_class, y_pred1_class))
print(accuracy_score(y_test_class, y_pred1_class))

[[1980   11]
 [ 439   70]]
              precision    recall  f1-score   support

           0       0.82      0.99      0.90      1991
           1       0.86      0.14      0.24       509

    accuracy                           0.82      2500
   macro avg       0.84      0.57      0.57      2500
weighted avg       0.83      0.82      0.76      2500

0.82
