<a href="https://colab.research.google.com/github/TanViCh0UhAn12/ML/blob/main/NLP_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NLP Classification**

**Text preprocessing**

*1. Importing Library & reading dataset*

In [5]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/5 April to 15 April and count....twitter_MBTI.csv')
df.head()

Unnamed: 0                                               text label
0           0  @Pericles216 @HierBeforeTheAC @Sachinettiyil T...  intj
1           1  @Hispanthicckk Being you makes you look cute||...  intj
2           2  @Alshymi Les balles sont réelles et sont tirée...  intj
3           3  I'm like entp but idiotic|||Hey boy, do you wa...  intj
4           4  @kaeshurr1 Give it to @ZargarShanif ... He has...  intj

*2. Analyzing dataset*

In [6]:
df.head()

Unnamed: 0                                               text label
0           0  @Pericles216 @HierBeforeTheAC @Sachinettiyil T...  intj
1           1  @Hispanthicckk Being you makes you look cute||...  intj
2           2  @Alshymi Les balles sont réelles et sont tirée...  intj
3           3  I'm like entp but idiotic|||Hey boy, do you wa...  intj
4           4  @kaeshurr1 Give it to @ZargarShanif ... He has...  intj

*3. Defining y*

In [7]:
y =df['label']

*4. Counting Unique values in y column*

In [8]:
df['label'].value_counts(), df['label'].nunique()

(infp    1282
 infj    1057
 intp     811
 intj     781
 enfp     729
 entp     577
 enfj     518
 isfp     367
 isfj     364
 istp     327
 entj     279
 istj     259
 esfp     174
 esfj     105
 estp     100
 estj      81
 Name: label, dtype: int64,
 16)

*5. Label Encoding*

In [9]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([10, 10, 10, ...,  3,  8, 15])

In [10]:
df.shape

(7811, 3)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7811 entries, 0 to 7810
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  7811 non-null   int64 
 1   text        7811 non-null   object
 2   label       7811 non-null   object
dtypes: int64(1), object(2)
memory usage: 183.2+ KB


*6. Lowercase for 4th row*

In [12]:
df['text'][4].lower()

"@kaeshurr1 give it to @zargarshanif ... he has pica since childhood|||@dannnyaaaa say qubool hai in my dm ❤️|||@dannnyaaaa get married asap|||@ubaid_rasool two decades actually 🌚|||@kaeshurr1 @umer__ayoub subas ?|||@kaeshurr1 @umer__ayoub wayne kar niyiv meati panas seyt|||@kaeshurr1 @umer__ayoub mea gov akh hafte czeaf dith|||@kaeshurr1 @umer__ayoub meati niyziha panas seyt|||okay 🥺 https://t.co/3fh1tqbfl2|||@hareembhat_ https://t.co/0nve1cdbqd|||@pingaapongaa hye|||@bint_e_tasleem i had a lot to speak out, but you ignored me 🥺|||@whytaniya welcome back|||just a simple thought, what's stopping from having icu facilities at dh shopian? 50-70% deaths occur due to referra… https://t.co/wpcgmdzsar|||@toyibanabi laxmi chit fund bank|||same bro same 🥺🌚 https://t.co/2g5zorfhsf|||@yawar_banday expecting a grand opening soon in sha allah???|||@dannnyaaaa aameeeeeeeennnn|||@babra_yousuf mohabat|||@yawar_banday thanks for bringing the coolest place ever seen ❤️|||@aadilsam118 mujhe b le jao tan

In [13]:
text =df['text']

*7. Coverting lowercase*

In [14]:
text = text.str.lower()

*8. Removing html tags*

In [15]:
import re 
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

In [16]:
text = text.apply(remove_html_tags)
text

0       @pericles216 @hierbeforetheac @sachinettiyil t...
1       @hispanthicckk being you makes you look cute||...
2       @alshymi les balles sont réelles et sont tirée...
3       i'm like entp but idiotic|||hey boy, do you wa...
4       @kaeshurr1 give it to @zargarshanif ... he has...
                              ...                        
7806    @sobsjjun god,,pls take care 😕|||@sobsjjun hir...
7807    @ignis_02 wow last time i got intp https://t.c...
7808    @akupilled a 100%|||@akupilled that someone wi...
7809    if you’re #intj this one is for you | what is ...
7810    @harry__lambert @gucci hey can you dm me a pic...
Name: text, Length: 7811, dtype: object

*9. Cleaning URL*

In [17]:
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\. \s+')
  return pattern.sub(r'',text)

In [18]:
text=text.apply(remove_url)
text

0       @pericles216 @hierbeforetheac @sachinettiyil t...
1       @hispanthicckk being you makes you look cute||...
2       @alshymi les balles sont réelles et sont tirée...
3       i'm like entp but idiotic|||hey boy, do you wa...
4       @kaeshurr1 give it to @zargarshanif ... he has...
                              ...                        
7806    @sobsjjun god,,pls take care 😕|||@sobsjjun hir...
7807    @ignis_02 wow last time i got intp    i think ...
7808    @akupilled a 100%|||@akupilled that someone wi...
7809    if you’re #intj this one is for you | what is ...
7810    @harry__lambert @gucci hey can you dm me a pic...
Name: text, Length: 7811, dtype: object

*10. Removing punctuations*

In [1]:
import time 

In [20]:
punc = '''!()-{}[];:'"\,<>./?|@#$%^&*_~'''

In [21]:
def remove_punctuation(text):
  for char in punc:
    text = text.replace(char, '')
  return text

In [22]:
text = text.apply(remove_punctuation)
text

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont réelles et sont tirées...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care 😕sobsjjun hiro emerg...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if you’re intj this one is for you  what is ne...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [23]:
start = time.time()
print(remove_punctuation(text))
time1 = time.time() - start
print(time1)

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont réelles et sont tirées...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care 😕sobsjjun hiro emerg...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if you’re intj this one is for you  what is ne...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object
0.02400374412536621


In [24]:
text[7806]

'sobsjjun godpls take care 😕sobsjjun hiro emergency room are you okay waitdafahoe zeharrrrrrr😭😭😭😭😭😭😭😭txtlomlsss ye0nyang oh my god thats 💔ye0nyang txtlomlsss did i liesoobinspolaroid i knownano h—\nsoule  grandma   r so cute😭my whole tl just 4 oomfs doing sum shit but i love itsoobinspolaroid is this u0x1bts plus i took a test yesterday and i am an intp ur so annoying0x1bts dude atleast speak in english what if he minds wtfsoobinspolaroid sobsjjun oh my godsoobinspolaroid sobsjjun who tf tells before stealing just steal when hes sleeping or sum shit 😭0x1bts soobinspolaroid what the fuck0x1bts soobinspolaroid  im intpi should stop making jokes  helpbeomthyusiast1 nooooo😭ye0nyang snakskdmkwkwmdmbeomthyusiast1 who said im jokingyeehawnjun im so funnytxtlomlsss rightt im so geniusox1gyuu sooo truecactigumi im so funnytxtlomlsss im geniuschoiseeker yesyuniberri yunnie twtstolen btwif a shark bites ubite back  youll still d1e but the shark would be like yo wtfinsoobinspolaroid i love kids to

*11. Handling Emojis*

In [25]:
!pip install emoji
import emoji
print(emoji.demojize(text[7606]))

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.9/240.9 kB 8.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for emoji: filename=emoji-2.2.0-py3-none-any.whl size=234926 sha256=f58e91b9e91abc3f06835cbf62e717057f5ae6668e882a874f6c1be0979ba503
  Stored in directory: /root/.cache/pip/wheels/9a/b8/0f/f580817231cbf59f6ade9fd132ff60ada1de9f7dc85521f857
Successfully built emoji
guys omg  so happy they got to meet again  sayangku :loudly_crying_face::loudly_crying_face::loudly_crying_face::loudly_crying_face:wetheboyz sayangi hope their arms is the last thing i see before i sleep and then i will be dreaming about sanghak arms toogoing crazy  one chance please give me one chance :face_with_hand_over_mouth::grinning_face_with_smiling_eyes::rolling_on_the_floor_laughing::beaming_face_with_smiling_eyes::face_holding_back_tears::grinning_squinting_face:guys i love haknyeon

In [26]:
text[7606].encode('utf-8')

b'guys omg  so happy they got to meet again  sayangku \xf0\x9f\x98\xad\xf0\x9f\x98\xad\xf0\x9f\x98\xad\xf0\x9f\x98\xadwetheboyz sayangi hope their arms is the last thing i see before i sleep and then i will be dreaming about sanghak arms toogoing crazy  one chance please give me one chance \xf0\x9f\xa4\xad\xf0\x9f\x98\x84\xf0\x9f\xa4\xa3\xf0\x9f\x98\x81\xf0\x9f\xa5\xb9\xf0\x9f\x98\x86guys i love haknyeon so muchsanghaakkkkkkkkkkkkk armsssssssssss\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84  ilywetheboyz omgwetheboyz juyeonliterally what the fucklord  shut up  hak ily\xf0\x9f\x98\x84\xf0\x9f\x98\x84  i love youwetheboyz omgoh my bbangnyuman\xe2\x80\xa6   am i suppose to move on what   baby  i love you so muchcravitystarship thank you youngtae \xf0\x9f\xab\xb6\xf0\x9f\xab\xb6\xf0\x9f\xab\xb6hey god its me again  my loveswetheboyz thank youwetheboyz oh my godbbangnyuanother win for me today as a fengfan and juyeon enthusi

In [27]:
type(text)

pandas.core.series.Series

In [28]:
test=[[text]]
text

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont réelles et sont tirées...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care 😕sobsjjun hiro emerg...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if you’re intj this one is for you  what is ne...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [29]:
text = pd.DataFrame(text)
text

text
0     pericles216 hierbeforetheac sachinettiyil the ...
1     hispanthicckk being you makes you look cutethi...
2     alshymi les balles sont réelles et sont tirées...
3     im like entp but idiotichey boy do you want to...
4     kaeshurr1 give it to zargarshanif  he has pica...
...                                                 ...
7806  sobsjjun godpls take care 😕sobsjjun hiro emerg...
7807  ignis02 wow last time i got intp    i think u ...
7808  akupilled a 100akupilled that someone will get...
7809  if you’re intj this one is for you  what is ne...
7810  harrylambert gucci hey can you dm me a pic of ...

[7811 rows x 1 columns]

In [30]:
type(text)

pandas.core.frame.DataFrame

In [31]:
import emoji
text=text.astype(str).apply(lambda x:x.str.encode('ascii','ignore').str.decode('latin-1'))

In [32]:
text.shape

(7811, 1)

In [33]:
text[7606:7607]

text
7606  guys omg  so happy they got to meet again  say...

In [34]:
text= text['text']

In [35]:
text.shape

(7811,)

In [36]:
type(text)

pandas.core.series.Series

In [37]:
text

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont relles et sont tires t...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care sobsjjun hiro emerge...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if youre intj this one is for you  what is nev...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [38]:
df['text']

0       @Pericles216 @HierBeforeTheAC @Sachinettiyil T...
1       @Hispanthicckk Being you makes you look cute||...
2       @Alshymi Les balles sont réelles et sont tirée...
3       I'm like entp but idiotic|||Hey boy, do you wa...
4       @kaeshurr1 Give it to @ZargarShanif ... He has...
                              ...                        
7806    @sobsjjun God,,pls take care 😕|||@sobsjjun Hir...
7807    @Ignis_02 wow last time i got intp https://t.c...
7808    @akupilled A 100%|||@akupilled That SOMEONE wi...
7809    If you’re #INTJ this one is for you | What is ...
7810    @harry__lambert @gucci hey can you dm me a pic...
Name: text, Length: 7811, dtype: object

**12. Tokenization**


In [39]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [40]:
text=pd.DataFrame(text)
text

text
0     pericles216 hierbeforetheac sachinettiyil the ...
1     hispanthicckk being you makes you look cutethi...
2     alshymi les balles sont relles et sont tires t...
3     im like entp but idiotichey boy do you want to...
4     kaeshurr1 give it to zargarshanif  he has pica...
...                                                 ...
7806  sobsjjun godpls take care sobsjjun hiro emerge...
7807  ignis02 wow last time i got intp    i think u ...
7808  akupilled a 100akupilled that someone will get...
7809  if youre intj this one is for you  what is nev...
7810  harrylambert gucci hey can you dm me a pic of ...

[7811 rows x 1 columns]

In [41]:
text['text']

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont relles et sont tires t...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care sobsjjun hiro emerge...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if youre intj this one is for you  what is nev...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [42]:
sent_tokenize

<function nltk.tokenize.sent_tokenize(text, language='english')>

In [43]:
import nltk
nltk.download('punkt')
word_tokenize= text['text'].apply(word_tokenize)
word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


0       [pericles216, hierbeforetheac, sachinettiyil, ...
1       [hispanthicckk, being, you, makes, you, look, ...
2       [alshymi, les, balles, sont, relles, et, sont,...
3       [im, like, entp, but, idiotichey, boy, do, you...
4       [kaeshurr1, give, it, to, zargarshanif, he, ha...
                              ...                        
7806    [sobsjjun, godpls, take, care, sobsjjun, hiro,...
7807    [ignis02, wow, last, time, i, got, intp, i, th...
7808    [akupilled, a, 100akupilled, that, someone, wi...
7809    [if, youre, intj, this, one, is, for, you, wha...
7810    [harrylambert, gucci, hey, can, you, dm, me, a...
Name: text, Length: 7811, dtype: object

In [44]:
text1=pd.DataFrame(word_tokenize)
text['text']

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont relles et sont tires t...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care sobsjjun hiro emerge...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if youre intj this one is for you  what is nev...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [45]:
text[7809:7810]

text
7809  if youre intj this one is for you  what is nev...

**FEATURE ENGINEERING**

*13. CountVectorizer*

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x1 = cv.fit_transform(text[7809:7810])
x1.shape

(1, 1)

In [47]:
x1

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [48]:
text[['text']]

text
0     pericles216 hierbeforetheac sachinettiyil the ...
1     hispanthicckk being you makes you look cutethi...
2     alshymi les balles sont relles et sont tires t...
3     im like entp but idiotichey boy do you want to...
4     kaeshurr1 give it to zargarshanif  he has pica...
...                                                 ...
7806  sobsjjun godpls take care sobsjjun hiro emerge...
7807  ignis02 wow last time i got intp    i think u ...
7808  akupilled a 100akupilled that someone will get...
7809  if youre intj this one is for you  what is nev...
7810  harrylambert gucci hey can you dm me a pic of ...

[7811 rows x 1 columns]

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x1 = cv.fit_transform(text['text'])
x1.shape

(7811, 736384)

In [50]:
x1

<7811x736384 sparse matrix of type '<class 'numpy.int64'>'
	with 4425728 stored elements in Compressed Sparse Row format>

In [51]:
from keras.utils import np_utils
npy = np_utils.to_categorical(y)
print(npy[:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x1, npy, test_size=.25, random_state=1)

In [53]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5858, 736384)
(1953, 736384)
(5858, 16)
(1953, 16)


In [54]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
x_train= sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [55]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5858, 736384)
(1953, 736384)
(5858, 16)
(1953, 16)


In [56]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

In [57]:
model = Sequential()
model.add(Dense(units=160, activation ='relu', input_dim=736384))
model.add(Dropout(0.1))
model.add(Dense(units =16, activation ='relu'))
model.add(Dropout(0.1))
model.add(Dense(units = 16, activation ='sigmoid'))

In [58]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [59]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 160)               117821600 
                                                                 
 dropout (Dropout)           (None, 160)               0         
                                                                 
 dense_1 (Dense)             (None, 16)                2576      
                                                                 
 dropout_1 (Dropout)         (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 16)                272       
                                                                 
Total params: 117,824,448
Trainable params: 117,824,448
Non-trainable params: 0
_________________________________________________________________


In [60]:
model.fit(x_train, y_train, epochs =1, verbose =1)

184/184 [==============================] - 674s 4s/step - loss: 2.7840 - accuracy: 0.1354


In [61]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/5 April to 15 April and count....twitter_MBTI.csv')
df.head()
y=df['label']

In [62]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(lowercase=True,stop_words='english',ngram_range=(1,1),tokenizer=None)
x = cv.fit_transform(text['text'])
x

<7811x736076 sparse matrix of type '<class 'numpy.int64'>'
	with 3612871 stored elements in Compressed Sparse Row format>

In [63]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y=lb.fit_transform(df['label'])
y

array([10, 10, 10, ...,  3,  8, 15])

In [64]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=.25)

In [65]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5858, 736076)
(1953, 736076)
(5858,)
(1953,)


**Implementing Model**

*14. Multinomial NB*

In [68]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
nb = MultinomialNB().fit(x_train, y_train)
nb

MultinomialNB()

In [69]:
nb.score(x_train,y_train)

0.5773301468077843

In [70]:
nb.score(x_test,y_test)

0.20378904249871993

In [71]:
#prediction
y_pred_nb = nb.predict(x_test)
print(len(y_pred_nb))
y_pred_nb

1953


array([9, 9, 9, ..., 9, 9, 9])

In [72]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [73]:
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))
print(accuracy_score(y_test, y_pred_nb))

[[  5   0   0   0   0   0   0   0  24  98   1   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0  27 151   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  17  53   1   0   0   0   0   0]
 [  0   0   1   2   0   0   0   0  15 123   7   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   6  17   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   2  39   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   3  16   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   1  20   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0  93 174   5   2   0   0   0   0]
 [  2   1   0   0   1   0   0   0  30 260   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0  49 124  14   0   0   0   0   0]
 [  0   2   0   0   0   0   0   0  22 167   5  14   0   0   0   0]
 [  0   0   0   0   0   0   0   0  19  75   2   0   1   0   0   0]
 [  0   0   0   0   0   0   0   0   9 103   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  12  48   5   0   0   0   2 

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
